#!/bin/bash

if [ "$2" = "" ]; then
	echo "Usage: $0 <width> <file1> [<file2>]"
	echo "output will be file1x, file2x"
	exit 1
fi

for i in "${@:2}"; do
	ext="${i##*.}"
	name="${i%.*}"
	newname="${name}x.${ext}"
	echo "converting [$i] to [$newname]"
	convert "$i" -resize $1 "$newname"
done
