#!/bin/bash

if [ "$1" == "" ]; then
	echo "specify --all to purge all docker logs or specify container name"
	exit 1
fi

if [ "$1" == "--all" ]; then
	truncate -s 0 /var/lib/docker/containers/*/*-json.log
else
	id=$(dk-id "$1")

	if [ "$?" == "0" ]; then
		truncate -s 0 /var/lib/docker/containers/$id/*-json.log
	fi
fi
